# Generated by Django 4.0.2 on 2022-03-08 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock_screener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.BooleanField(default=False)),
                ('maS', models.CharField(choices=[('SMA', 'Simple Moving Average'), ('EMA', 'Exponential Moving Average')], default='SMA', max_length=3)),
                ('maL', models.CharField(choices=[('SMA', 'Simple Moving Average'), ('EMA', 'Exponential Moving Average')], default='SMA', max_length=3)),
                ('maWS', models.IntegerField(default=15)),
                ('maWL', models.IntegerField(default=45)),
                ('psar', models.BooleanField(default=False)),
                ('psarAF', models.FloatField(default=0.02)),
                ('psarMA', models.FloatField(default=0.2)),
                ('adx', models.BooleanField(default=False)),
                ('adxW', models.IntegerField(default=18)),
                ('adxL', models.IntegerField(default=20)),
                ('srsi', models.BooleanField(default=False)),
                ('srsiW', models.IntegerField(default=21)),
                ('srsiSm1', models.IntegerField(default=3)),
                ('srsiSm2', models.IntegerField(default=3)),
                ('srsiOB', models.FloatField(default=0.8)),
                ('srsiOS', models.FloatField(default=0.2)),
                ('macd', models.BooleanField(default=False)),
                ('macdF', models.IntegerField(default=24)),
                ('macdS', models.IntegerField(default=52)),
                ('macdSm', models.IntegerField(default=9)),
            ],
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=5)),
                ('stock_full', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='savedsearch',
            constraint=models.UniqueConstraint(fields=('stock', 'user'), name='unique_searches'),
        ),
    ]
