# Generated by Django 4.0.2 on 2022-03-08 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_screener', '0002_signalconstructor_savedsearch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalconstructor',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
