# Generated by Django 4.0.2 on 2022-03-09 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_screener', '0005_remove_signalconstructor_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalconstructor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savedSignal', to=settings.AUTH_USER_MODEL),
        ),
    ]
