# Generated by Django 4.0.2 on 2022-04-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_screener', '0006_signalconstructor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalconstructor',
            name='adxW',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='signalconstructor',
            name='maWL',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='signalconstructor',
            name='macdF',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='signalconstructor',
            name='macdS',
            field=models.IntegerField(default=26),
        ),
        migrations.AlterField(
            model_name='signalconstructor',
            name='macdSm',
            field=models.IntegerField(default=210),
        ),
        migrations.AlterField(
            model_name='signalconstructor',
            name='srsiW',
            field=models.IntegerField(default=13),
        ),
    ]
